image: java:8

stages:
  - build

build:
  stage: build
  script: 
  - cd apiGestionEcole/
  - chmod +x ./mvnw
  - ./mvnw clean package
  artifacts:
    paths:
      - target/apiGestionEcole-0.0.1-SNAPSHOT.jar
